#!/usr/bin/env python2.7

import sys

def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in xrange(0, len(l), n):
        yield l[i:i + n]

def print_format_table():
    """
    prints table of formatted text format options
    """

    # All valid styles, foregrounds and backgrounds
    backgrounds = range(40, 48) + [49] + range(100, 108)
    styles = range(9) + range(21, 29)
    foregrounds = range(30, 38) + [39] + range(90, 98)

    for bg in backgrounds:
        for s in styles:
            fg_pieces = chunks(foregrounds, 6)

            for fg_piece in fg_pieces:
                for fg in fg_piece:
                    format_str = ';'.join([str(s), str(fg), str(bg)])
                    pad_len = 10 - len(format_str)
                    sys.stdout.write('\x1b[%sm%s\x1b[0m%s' % (format_str, format_str, "".ljust(pad_len)))

                sys.stdout.write("\n")

        sys.stdout.write("".ljust(60, "=") + "\n")

print_format_table()